### ISSUE TITLE
No account for team "FKLQTR48YQ"

### ISSUE THREAD

**Issue by namnm** [react-native-community/clipboard#44]
## Platforms

iOS

## Versions

- Android:
- iOS:
- react-native-netinfo:
- react-native:
- react:

## Reproducible Demo

Build error on iOS: 
No account for team "FKLQTR48YQ". (Add a new account in the Accounts preference pane or verify that your accounts have valid credentials.)

**Comment by matheuscuba** [comment]
That's not a library bug, this is a Xcode error message, you can check more here on this [question on StackOverflow](https://stackoverflow.com/questions/48584288/code-signing-no-account-for-team-message-when-signing-for-different-developer/50424214)

**Comment by namnm** [comment]
@matheuscuba No, because this repo include the team id here: https://github.com/react-native-community/clipboard/blob/92844309a578715809ff0be047c637fee30bdb65/ios/RNCClipboard.xcodeproj/project.pbxproj#L237
This is not my team id. May be from one of the maintainers of this repo.

**Comment by Naturalclar** [comment]
@namnm published 1.2.2 with fix included :tada:
