### ISSUE TITLE
null is not an object (evaluating 'u.default.setString')

### ISSUE THREAD

**Issue by LNFWebsite** [react-native-community/clipboard#53]
## Getting error `null is not an object (evaluating 'u.default.setString')` on using sample code in expo

No matter what I try, I'm getting the above error on trying to call the setString method via `Clipboard.setString()`. The same error appears on running the sample code in snack.expo

Here is the exact code that I used in expo:

```
import React, { useState } from 'react'
import { SafeAreaView, View, Text, TouchableOpacity, StyleSheet } from 'react-native'
import Clipboard from '@react-native-community/clipboard'

export default function App() {
  const [copiedText, setCopiedText] = useState('')

  const copyToClipboard = () => {
    Clipboard.setString('hello world')
  }

  const fetchCopiedText = async () => {
    const text = await Clipboard.getString()
    setCopiedText(text)
  }

  return (
    <SafeAreaView style={{ flex: 1 }}>
      <View style={styles.container}>
        <TouchableOpacity onPress={() => copyToClipboard()}>
          <Text>Click here to copy to Clipboard</Text>
        </TouchableOpacity>
        <TouchableOpacity onPress={() => fetchCopiedText()}>
          <Text>View copied text</Text>
        </TouchableOpacity>

        <Text style={styles.copiedText}>{copiedText}</Text>
      </View>

    </SafeAreaView>
  )
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center'
  },
  copiedText: {
    marginTop: 10,
    color: 'red'
  }
})
```

Thanks ahead!

**Comment by LNFWebsite** [comment]
Nevermind, it's not included in the Expo SDK yet.

**Comment by Jorciney** [comment]
I had the same issue with Android.
Weird enough I had to do a pod install:
`cd ios && pod install && cd ../`
after that, I ran `react-native run-android` and it worked.

**Comment by danieltgfischer** [comment]
Neither expo or community's clipboard worked for me. I'm using deprecated Clipboard of react-native and expo bare workflow

**Comment by iralitv** [comment]
You need also run the following command according the [official docs](https://github.com/react-native-clipboard/clipboard):
- for React Native <= 0.59 **react-native link @react-native-clipboard/clipboard**
- for React Native v0.60+ **npx pod-install** (you need preinstall **pod**)

Or maybe run these two commands one by one regardless of RN version (that option works for me)

**Comment by monkeyK1n9** [comment]
For those facing this issue in expo like @LNFWebsite or @danieltgfischer , there is an expo package which you can use, [here](https://docs.expo.dev/versions/latest/sdk/clipboard/).

Hope this will solve your issue.
