### ISSUE TITLE
Error upon Clipboard.setString

### ISSUE THREAD

**Issue by NickTheTurtle** [react-native-community/clipboard#66]
## Ask your Question
I did npm install and pod install. Then I called Clip.setString. However, I'm getting this error:

<img width="330" alt="Screen Shot 2020-08-05 at 10 36 13 PM" src="https://user-images.githubusercontent.com/12247846/89487865-32fb6f00-d76c-11ea-84ea-cfa5317371d0.png">

I'm not sure what this means. How do I solve this? Thanks!

**Comment by firdaussoberi** [comment]
I also had the same issue and it breaks my production app. What's weird is it works fine on one Android9 phone (Redmi Note7) and not the other running Android9 (Galaxt Note 8). Android10 straight out gives similar error. Using RN0.60.4

**Comment by NickTheTurtle** [comment]
Never mind. I was being stupid. It only works on physical device.
